/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_de_.n2;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADM-TI
 */
public class janela_devolucao extends javax.swing.JFrame {

    /**
     * Creates new form janela_devolucao
     */
    public janela_devolucao() {
        initComponents();
        CNN c = new CNN();
        c.conect();
        try {
            ResultSet rs = c.stm.executeQuery("SELECT * FROM cliente");

            while (rs.next()) {
                int codigo = rs.getInt("id");
                String nome = rs.getString("nome_cli");
                String telefone = rs.getString("telefone");
                String email = rs.getString("email");

                Cliente cli = new Cliente(codigo, nome, telefone, email);
                cli.getCodigo();

                CMBCliented.addItem(cli);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Janela_Cad_loca.class.getName()).log(Level.SEVERE, null, ex);
        }

        
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CMBCliented = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CMBveiculo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtdata_dv = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Cliente");

        CMBCliented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBClientedActionPerformed(evt);
            }
        });

        jLabel2.setText("Veiculo");

        jLabel5.setText("Data devolução");

        try {
            txtdata_dv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("Devolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CMBveiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addComponent(CMBCliented, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtdata_dv, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CMBCliented, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CMBveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdata_dv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMBClientedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBClientedActionPerformed

    }//GEN-LAST:event_CMBClientedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String data_dv = txtdata_dv.getText();
        CNN l = new CNN();
        l.conect();
        locacao tempD = (locacao) CMBveiculo.getSelectedItem();
        
        String sqlUpd = "UPDATE locacao SET data_dev = '" + data_dv +"' WHERE id_veiculo = " + tempD.getVeiculo().getCodigo_v();
        
        String sqlUp = "UPDATE veiculo SET statusloca = 'n' WHERE id = " + tempD.getVeiculo().getCodigo_v();
        String sqlupS = "UPDATE locacao SET status_loca = 'D' WHERE id = " + tempD.getCod_Loca();
        try {
            l.stm.executeUpdate(sqlUpd);
            l.stm.executeUpdate(sqlUp);
            l.stm.executeUpdate(sqlupS);
            JOptionPane.showMessageDialog(null, "Incluido com Sucesso");
       
        } catch (SQLException ex) {
            Logger.getLogger(Janlea_Cadastra_Cli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       pesquisa();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void pesquisa(){
        CNN c = new CNN();
        c.conect();
        Cliente temp = (Cliente) CMBCliented.getSelectedItem();
        
        try {
            ResultSet rs = c.stm.executeQuery("SELECT l.id, l.id_cliente,l.id_veiculo, c.nome_cli, v.placa, v.modelo, l.status_loca, l.data_loca, l.data_dev FROM  locacao l, cliente c, veiculo v WHERE l.id_cliente = c.id  AND L.id_veiculo = v.id");

            while (rs.next()) {
                int cod_loca = rs.getInt("id");
                int cliente = rs.getInt("id_cliente");
                int veiculo  = rs.getInt("id_veiculo");
                String status_loca = rs.getString("status_loca");
                
                Veiculo vTemp = new Veiculo(veiculo, rs.getString("placa"), "", "", "");
                Cliente cTemp = new Cliente (cliente, rs.getString("nome_cli"), "", "");
                
                String dataL = rs.getString("data_loca");
                String dataD = rs.getString("data_dev");
                
               locacao loc = new locacao (cod_loca, cTemp, vTemp, "","",status_loca);
                
                if (temp.getCodigo() == rs.getInt("id_cliente") && rs.getString("status_loca").equalsIgnoreCase("E")) {
                    CMBveiculo.addItem(loc);

                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(janela_devolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janela_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janela_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janela_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janela_devolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janela_devolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Cliente> CMBCliented;
    private javax.swing.JComboBox<locacao> CMBveiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField txtdata_dv;
    // End of variables declaration//GEN-END:variables
}
