/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_de_.n2;

import java.io.Reader;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Italo
 */
public class Janela_Cad_loca extends javax.swing.JFrame {
    janela_devolucao jd = new janela_devolucao();

    public Janela_Cad_loca() {
        initComponents();
        CNN c = new CNN();
        c.conect();
        try {
            ResultSet rs = c.stm.executeQuery("SELECT * FROM cliente");

            while (rs.next()) {
                int codigo = rs.getInt("id");
                String nome = rs.getString("nome_cli");
                String telefone = rs.getString("telefone");
                String email = rs.getString("email");

                Cliente cli = new Cliente(codigo, nome, telefone, email);
                cli.getCodigo();
                CMBCliente.addItem(cli);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Janela_Cad_loca.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ResultSet rv = c.stm.executeQuery("SELECT * FROM veiculo");

            while (rv.next()) {
                String statusLoca = rv.getString("statusloca");
                int codigo_v = rv.getByte("id");
                String placa = rv.getString("placa");
                String marcaV = rv.getString("marca");
                String modeloV = rv.getString("modelo");
                int codV = rv.getInt("id");
                if (statusLoca.equalsIgnoreCase("n")) {
                    Veiculo v = new Veiculo(codigo_v, placa, marcaV, modeloV, statusLoca);
                    CMBVeiculo.addItem(v);
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Janela_Cad_loca.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTCod_loca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CMBCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CMBVeiculo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        DataLoca = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setText("Cod_Locação");

        jLabel2.setText("Cliente ");

        CMBCliente.setModel(CMBCliente.getModel());

        jLabel3.setText("Veiculo");

        CMBVeiculo.setModel(CMBVeiculo.getModel());
        CMBVeiculo.setSelectedItem(CMBVeiculo);

        jLabel4.setText("Data Locação");

        try {
            DataLoca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        DataLoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataLocaActionPerformed(evt);
            }
        });

        jButton1.setText("Incluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Cliente", "Placa", "Modelo", "Status", "Data Locação", "Data Devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jButton2.setText("Gerrar Relatorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Devolução");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTCod_loca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DataLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCod_loca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DataLoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataLocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataLocaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataLocaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int cod = Integer.parseInt(TXTCod_loca.getText());
        Cliente temp = (Cliente) CMBCliente.getSelectedItem();
        Veiculo tempv = (Veiculo) CMBVeiculo.getSelectedItem();
        String dataloca = DataLoca.getText();

        CNN l = new CNN();
        l.conect();

        String sql = "INSERT INTO locacao VALUES('" + cod + "', '" + temp.getCodigo() + "', '" + tempv.getCodigo_v() + "', '" + dataloca + "', " + "'E')";
        String sqlUp = "UPDATE veiculo SET statusloca = 's' WHERE id = " + tempv.getCodigo_v();
        try {
            l.stm.executeUpdate(sql);
            l.stm.executeUpdate(sqlUp);
            JOptionPane.showMessageDialog(null, "Incluido com Sucesso");
            atualizartabela();
        } catch (SQLException ex) {
            Logger.getLogger(Janlea_Cadastra_Cli.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        atualizartabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
             jd.setVisible(true);// Chama a Janela principal:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void atualizartabela() {

        CNN d = new CNN();
        d.conect();//Abre a conexão com banco;

        try {
            ResultSet rs = d.stm.executeQuery("SELECT l.id, c.nome_cli, v.placa, v.modelo, l.status_loca, l.data_loca, l.data_dev FROM  locacao l, cliente c, veiculo v WHERE l.id_cliente = c.id  AND L.id_veiculo = v.id");//Cria a sintax de select no banco;//Executa a sintax de insert dentro do banco;

            DefaultTableModel modelo
                    = (DefaultTableModel) Tabela.getModel();

            int rows = modelo.getRowCount();

            for (int i = rows - 1; i >= 0; i--) {
                modelo.removeRow(i);
            }

            while (rs.next()) {
                int cod = rs.getInt("id");
                String nome_cli = rs.getString("nome_cli");
                String placa = rs.getString("placa");
                String modeloV = rs.getString("modelo");
                String status = rs.getString("status_loca");
                String dataL = rs.getString("data_loca");
                String dataD = rs.getString("data_dev");

                modelo.addRow(new Object[]{
                    cod,
                    nome_cli,
                    placa,
                    modeloV,
                    status,
                    dataL,
                    dataD
                });

            }
        } catch (SQLException ex) {
            Logger.getLogger(Janlea_Cadastra_Cli.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Cad_loca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Cad_loca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Cad_loca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Cad_loca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_Cad_loca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Cliente> CMBCliente;
    private javax.swing.JComboBox<Veiculo> CMBVeiculo;
    private javax.swing.JFormattedTextField DataLoca;
    private javax.swing.JTextField TXTCod_loca;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
